#ifndef FX_COMP_CONSTANTS
#define FX_COMP_CONSTANTS

#define HEADLESS_FALLBACK_OUTPUT_WIDTH 800
#define HEADLESS_FALLBACK_OUTPUT_HEIGHT 600

#define EFFECTS_CORNER_RADII 14

#define TOPLEVEL_NON_MAIN_OUTPUT_OPACITY 0.4

/*
 * Titlebar
 */

#define TITLEBAR_COLOR_BACKGROUND_FOCUSED 0xFF303030
#define TITLEBAR_COLOR_BACKGROUND_UNFOCUSED 0xFF202020
#define TITLEBAR_COLOR_FOREGROUND_FOCUSED 0xFFffffff
#define TITLEBAR_COLOR_FOREGROUND_UNFOCUSED 0xFF888888
#define TITLEBAR_COLOR_BORDER_FOCUSED 0xFF5d5d5d
#define TITLEBAR_COLOR_BORDER_UNFOCUSED 0xFF4b4b4b

// Close Button
#define TITLEBAR_COLOR_BUTTON_CLOSE_FOCUSED 0xFFe34e4b
#define TITLEBAR_COLOR_BUTTON_CLOSE_UNFOCUSED 0xFF525252
#define TITLEBAR_COLOR_BUTTON_CLOSE_HOVER 0xFFe34e4b
#define TITLEBAR_COLOR_BUTTON_CLOSE_FOREGROUND 0xFF710407
#define TITLEBAR_BUTTON_CLOSE_ICON_NAME "window-close-symbolic"
#define TITLEBAR_BUTTON_CLOSE_ICON_PADDING 2
// Fullscreen Button
#define TITLEBAR_COLOR_BUTTON_FULLSCREEN_FOCUSED 0xFF2eb341
#define TITLEBAR_COLOR_BUTTON_FULLSCREEN_UNFOCUSED 0xFF525252
#define TITLEBAR_COLOR_BUTTON_FULLSCREEN_HOVER 0xFF2eb341
#define TITLEBAR_COLOR_BUTTON_FULLSCREEN_FOREGROUND 0xFF11581f
#define TITLEBAR_BUTTON_FULLSCREEN_ICON_NAME "window-maximize-symbolic"
#define TITLEBAR_BUTTON_FULLSCREEN_ICON_PADDING 2
// Minimize Button
#define TITLEBAR_COLOR_BUTTON_MINIMIZE_FOCUSED 0xFFe4a93a
#define TITLEBAR_COLOR_BUTTON_MINIMIZE_UNFOCUSED 0xFF525252
#define TITLEBAR_COLOR_BUTTON_MINIMIZE_HOVER 0xFFe4a93a
#define TITLEBAR_COLOR_BUTTON_MINIMIZE_FOREGROUND 0xFF894e10
#define TITLEBAR_BUTTON_MINIMIZE_ICON_NAME "window-minimize-symbolic"
#define TITLEBAR_BUTTON_MINIMIZE_ICON_PADDING 2

#define TITLEBAR_BUTTON_SIZE 14
#define TITLEBAR_BUTTON_BORDER_THICKNESS 1
#define TITLEBAR_BUTTON_MARGIN 6
#define TITLEBAR_BUTTON_SPACING 12
#define TITLEBAR_BUTTONS_ON_RIGHT false
#define TITLEBAR_BUTTONS_ALWAYS_VISIBLE false
#define TITLEBAR_SEPARATOR_HEIGHT 1
#define TITLEBAR_TEXT_ELLIPSE_STRING "…"
#define TITLEBAR_TEXT_SIZE 14
#define TITLEBAR_TEXT_FONT "Clear Sans"

#define BORDER_WIDTH 1
#define BORDER_RESIZE_WIDTH 10

#define FLOATING_MOD WLR_MODIFIER_ALT

#endif // !FX_COMP_CONSTANTS
