#ifndef FX_COMP_CONSTANTS
#define FX_COMP_CONSTANTS

#define EXT_FOREIGN_TOPLEVEL_LIST_VERSION 1
#define WL_COMPOSITOR_VERSION 6
#define XDG_SHELL_VERSION 6
#define LAYER_SHELL_VERSION 4

#define NSEC_IN_SECONDS (long)1000000000

#define TRANSACTION_TIME_MS 200

#define HEADLESS_FALLBACK_OUTPUT_WIDTH 800
#define HEADLESS_FALLBACK_OUTPUT_HEIGHT 600

#define EFFECTS_CORNER_RADII 14
#define BLUR_RADIUS 8
#define BLUR_PASSES 3

#define TERM "kitty"


/*
 * Overlays
 */

#define OVERLAY_COLOR_BACKGROUND 0x242424CC
#define OVERLAY_COLOR_FOREGROUND 0xFFFFFFFF
#define OVERLAY_PADDING 8

/*
 * Workspace Switcher
 */

#define WORKSPACE_SWITCHER_COLOR_FOCUSED_BACKGROUND 0x303030CC
#define WORKSPACE_SWITCHER_COLOR_FOCUSED_FOREGROUND 0xFFFFFFCC
#define WORKSPACE_SWITCHER_COLOR_UNFOCUSED_BACKGROUND 0x888888CC
#define WORKSPACE_SWITCHER_COLOR_UNFOCUSED_FOREGROUND 0x202020CC
#define WORKSPACE_SWITCHER_VISIBLE_MS 1000
#define WORKSPACE_SWITCHER_FADE_IN_MS 50
#define WORKSPACE_SWITCHER_FADE_OUT_MS 150
#define WORKSPACE_SWITCHER_ITEM_WIDTH 100
#define WORKSPACE_SWITCHER_ITEM_HEIGHT 100

/*
 * Lock
 */

#define LOCK_ANIMATION_FADE_DURATION_MS 400

/*
 * Toplevel
 */

#define TOPLEVEL_NON_MAIN_OUTPUT_OPACITY 0.4
#define TOPLEVEL_SHADOW_COLOR 0x00000080
#define TOPLEVEL_SHADOW_BLUR_SIGMA 30
#define TOPLEVEL_SHADOW_X_OFFSET 0
#define TOPLEVEL_SHADOW_Y_OFFSET 20
#define TOPLEVEL_ANIMATION_OPEN_CLOSE_DURATION_MS 250
#define TOPLEVEL_ANIMATION_RESIZE_DURATION_MS 250

/*
 * Titlebar
 */

#define TITLEBAR_COLOR_BACKGROUND_FOCUSED 0x303030FF
#define TITLEBAR_COLOR_BACKGROUND_UNFOCUSED 0x202020FF
#define TITLEBAR_COLOR_FOREGROUND_FOCUSED 0xFFFFFFFF
#define TITLEBAR_COLOR_FOREGROUND_UNFOCUSED 0x888888FF
#define TITLEBAR_COLOR_BORDER_FOCUSED 0x14151ABF
#define TITLEBAR_COLOR_BORDER_UNFOCUSED 0x14151ABF
#define TITLEBAR_COLOR_INNER_BORDER 0xFFFFFF20

// Close Button
#define TITLEBAR_COLOR_BUTTON_CLOSE_FOCUSED 0xe34e4bFF
#define TITLEBAR_COLOR_BUTTON_CLOSE_UNFOCUSED 0x525252FF
#define TITLEBAR_COLOR_BUTTON_CLOSE_HOVER 0xe34e4bFF
#define TITLEBAR_COLOR_BUTTON_CLOSE_FOREGROUND 0x710407FF
#define TITLEBAR_BUTTON_CLOSE_ICON_NAME "window-close-symbolic"
#define TITLEBAR_BUTTON_CLOSE_ICON_PADDING 2
// Fullscreen Button
#define TITLEBAR_COLOR_BUTTON_FULLSCREEN_FOCUSED 0x2eb341FF
#define TITLEBAR_COLOR_BUTTON_FULLSCREEN_UNFOCUSED 0x525252FF
#define TITLEBAR_COLOR_BUTTON_FULLSCREEN_HOVER 0x2eb341FF
#define TITLEBAR_COLOR_BUTTON_FULLSCREEN_FOREGROUND 0x11581fFF
#define TITLEBAR_BUTTON_FULLSCREEN_ICON_NAME "window-maximize-symbolic"
#define TITLEBAR_BUTTON_FULLSCREEN_ICON_PADDING 2
// Minimize Button
#define TITLEBAR_COLOR_BUTTON_MINIMIZE_FOCUSED 0xe4a93aFF
#define TITLEBAR_COLOR_BUTTON_MINIMIZE_UNFOCUSED 0x525252FF
#define TITLEBAR_COLOR_BUTTON_MINIMIZE_HOVER 0xe4a93aFF
#define TITLEBAR_COLOR_BUTTON_MINIMIZE_FOREGROUND 0x894e10FF
#define TITLEBAR_BUTTON_MINIMIZE_ICON_NAME "window-minimize-symbolic"
#define TITLEBAR_BUTTON_MINIMIZE_ICON_PADDING 2

#define TITLEBAR_BUTTON_SIZE 14
#define TITLEBAR_BUTTON_BORDER_THICKNESS 1
#define TITLEBAR_BUTTON_MARGIN 6
#define TITLEBAR_BUTTON_SPACING 12
#define TITLEBAR_BUTTONS_ON_RIGHT false
#define TITLEBAR_BUTTONS_ALWAYS_VISIBLE false
#define TITLEBAR_SEPARATOR_HEIGHT 1
#define TITLEBAR_TEXT_SIZE 14
#define TITLEBAR_TEXT_FONT "Clear Sans"

#define BORDER_WIDTH 1
#define INNER_BORDER_WIDTH 2
#define BORDER_RESIZE_WIDTH 10

#define FLOATING_MOD WLR_MODIFIER_ALT

/*
 * Input
 */

#define INPUT_KB_REPEAT_DELAY 250
#define INPUT_KB_REPEAT_RATE 30
#define INPUT_KB_XKB_LAYOUT "se"
#define INPUT_KB_XKB_RULES NULL
#define INPUT_KB_XKB_MODEL NULL
#define INPUT_KB_XKB_OPTIONS NULL
#define INPUT_KB_XKB_VARIANT NULL

#define INPUT_POINTER_ACCEL_PROFILE "flat"
#define INPUT_POINTER_CLICK_METHOD (int)LIBINPUT_CONFIG_CLICK_METHOD_CLICKFINGER
#define INPUT_POINTER_TAP_METHOD (int)LIBINPUT_CONFIG_TAP_DISABLED
#define INPUT_POINTER_TAP_BUTTON_METHOD (int)LIBINPUT_CONFIG_TAP_MAP_LMR
#define INPUT_POINTER_DRAG (int)LIBINPUT_CONFIG_DRAG_ENABLED
#define INPUT_POINTER_DRAG_LOCK (int)LIBINPUT_CONFIG_DRAG_LOCK_ENABLED
#define INPUT_POINTER_DWT (int)LIBINPUT_CONFIG_DWT_ENABLED
#define INPUT_POINTER_DWTP (int)LIBINPUT_CONFIG_DWTP_ENABLED
#define INPUT_POINTER_EVENTS                                                   \
	(int)LIBINPUT_CONFIG_SEND_EVENTS_DISABLED_ON_EXTERNAL_MOUSE
#define INPUT_POINTER_LEFT_HANDED false
#define INPUT_POINTER_MIDDLE_EMULATION                                         \
	(int)LIBINPUT_CONFIG_MIDDLE_EMULATION_ENABLED
#define INPUT_POINTER_NATURAL_SCROLL true
#define INPUT_POINTER_ACCEL_SPEED (double)-0.5
#define INPUT_POINTER_SCROLL_METHOD (int)LIBINPUT_CONFIG_SCROLL_2FG

#endif // !FX_COMP_CONSTANTS
